name: Terraform Apply on PR

on:
  pull_request:
    branches:
      - main  # Solo se activa en PRs hacia la rama main

jobs:
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    environment: terraform  # Referencia el environment que creaste

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5  # Cambia esto a la versión de Terraform que uses

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # Secret con las credenciales de GCP

      - name: Set up GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Determine PR branch
        id: pr-branch
        run: |
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "PR branch: $PR_BRANCH"
          echo "pr_branch=$PR_BRANCH" >> $GITHUB_OUTPUT

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./${{ steps.pr-branch.outputs.pr_branch }}  # Usa la rama de origen del PR

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./${{ steps.pr-branch.outputs.pr_branch }}  # Usa la rama de origen del PR
